# ch2. ndarray 생성하기 

이번 챕터에서는 numpy에서 다차원 배열을 다루는 가장 기본인 ndarray를 직접 만들어보겠습니다.  
그리고 ndarray의 기본 조작법을 배워보겠습니다.

## ndarray 만들기

### python list를 이용해서 ndarray 생성

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [50]:
a = np.array([
    [1,2],
    [3,4]
])

a

array([[1, 2],
       [3, 4]])

In [48]:
type(a)

numpy.ndarray

In [49]:
a.shape

(2, 2)

### np.zeros
0으로 채워진 ndarray 리턴

In [15]:
# np.zeros 함수 안에 shape 넣어주는 것
# 2x2 matrix가 3개 

np.zeros([3,2,2])


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [18]:
a = np.zeros([3,2,2])
type(a[0][0][0])    # 64비트로 표현된 실수

numpy.float64

In [20]:
a = np.zeros([3,2,2], dtype=np.int64)
type(a[0][0][0]) 

numpy.int64

### np.ones
1로 채워진 ndarray 리턴

In [22]:
np.ones([2,3], dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

### np.full
특정 값으로 채워진 ndarray 리턴

In [23]:
np.full([3,2],5)


array([[5, 5],
       [5, 5],
       [5, 5]])

In [24]:
# 무한대를 나타낼 때 
np.full([3,2],np.inf)

array([[inf, inf],
       [inf, inf],
       [inf, inf]])

In [25]:
# 무한대를 나타낼 때 
np.full([3,2],-np.inf)

array([[-inf, -inf],
       [-inf, -inf],
       [-inf, -inf]])

### np.arange
특정 간격으로 채워진 ndarray 생성

In [27]:
# 자주씀

np.arange(1,9,1)   
# 시작 숫자, 마지막-1 숫자, 1간격으로

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.arange(1,9,2)   

array([1, 3, 5, 7])

In [57]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### 연습문제
np.ones, np.zeros, np.fulls를 사용하여 아래 형태의 ndarray를 생성하시오.

In [44]:
np.ones([2,2,2],dtype=np.int64)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int64)

In [37]:
np.zeros([2,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [41]:
np.full([3,3],5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [45]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])