# ch5. ndarray 연산
numpy ndarray도 더하고 빼기 연산을 할 수 있습니다.

### ndarray와 숫자 (스칼라값) 간의 연산
ndarray는 숫자와 더하기, 빼기, 나누기, 곱하기가 가능합니다. 이 때, ndarray의 모든 요소들에 해당 숫자 연산이 적용됩니다.

In [1]:
import numpy as np

In [2]:
a = np.arange(1, 9, 1).reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
a + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [6]:
a - 2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [4]:
a * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [7]:
a / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [8]:
a % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0]], dtype=int32)

In [9]:
a.astype(np.int32)   # 데이터타입 변환하는 로직은 넘파이에 있음 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### ndarray 간 연산
차원이 동일한 ndarray 간에는 사칙 연산이 가능합니다. 이 때는 ndarray의 동일한 인덱스끼리 연산을 수행합니다.

In [11]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
b = np.arange(9,17,1).reshape([2,4])
b

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
c= np.arange(18,26,1)
c

array([18, 19, 20, 21, 22, 23, 24, 25])

In [14]:
# shpae이 같으면 연산 가능
a + b 

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [15]:
a - b

array([[-8, -8, -8, -8],
       [-8, -8, -8, -8]])

In [16]:
a * b

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [17]:
a % b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# a + c
# error : perands could not be broadcast together with shapes 
# shape 이 안 맞아서 에러

### numpy boolean 연산
ndarray에 부등식 연산을 수행하면 각 원소에 대해서 부등식을 만족하는지 여부를 boolean 값으로 채워준 ndarray를 리턴합니다.

In [21]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
a > 4

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [23]:
 a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True]])

이렇게 구한 boolean 값으로 채워진 ndarray는 인덱스처럼 사용할 수 있습니다.

In [24]:
a[a % 2 == 0]

array([2, 4, 6, 8])

In [25]:
a[a<4]

array([1, 2, 3])

혹은 np.where를 사용하면 True인 값의 인덱스를 구할 수 있습니다.

In [26]:
np.where(a>4)

(array([1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3], dtype=int64))

np.where를 통해 구한 값을 다시 인덱스로 사용할 수도 있다.

In [27]:
a[np.where(a>4)]

array([5, 6, 7, 8])

## 연습문제

ndarray 연산을 이용해서 아래와 같은 출력을 구해보세요.

In [40]:
import numpy as np

a = np.arange(1, 19, 2).reshape([3,3])
b = np.arange(2, 20, 2).reshape([3,3])
a, b

(array([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

In [29]:
a + b

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [30]:
a - b

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [43]:
(2*a) + b

array([[ 4, 10, 16],
       [22, 28, 34],
       [40, 46, 52]])

In [33]:
a[a > 10]

array([11, 13, 15, 17])

In [35]:
b[b < 10]

array([2, 4, 6, 8])