## 복습 퀴즈

In [2]:
import numpy as np

### 아래 ndarray들을 생성해보세요

In [4]:
np.array([[1,3],[5,3]])

array([[1, 3],
       [5, 3]])

In [8]:
np.ones([2,2,3], dtype=np.int32)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [10]:
np.full([2,3],3)

array([[3, 3, 3],
       [3, 3, 3]])

In [45]:
np.arange(100,200,5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

### 주어진 ndarray의 형태를 reshape와 transpose를 이용해서 바꿔보세요

In [12]:
sample = np.arange(1, 17, 1)

In [13]:
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [14]:
sample.reshape([2,4,2])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [24]:
sample.reshape([4,4])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
sample.reshape([4,4]).transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

### 축을 이용한 접근으로 주어진 ndarray에서 해당 값들을 찾아보세요

In [32]:
sample = np.arange(1, 17, 1).reshape(4, 2, 2)

In [33]:
sample

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [35]:
sample[:,1]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [43]:
sample[:,:,1]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [44]:
sample[:,:,1].flatten()

array([ 2,  4,  6,  8, 10, 12, 14, 16])