# ch3. ndarray 형태 변경하기
np.reshape, np.transpose 등의 함수를 이용하면 다차원 배열의 형태를 원하는 대로 변경할 수 있습니다.

### np.reshape
ndarray를 원하는 형태로 지정하여 변경할 수 있습니다. 단, 이 때 변경 전과 변경 후의 다차원 배열의 원소 개수가 동일하게 유지되어야 합니다.  
ex) 3 x4 -> 2 x 6

In [1]:
import numpy as np

In [3]:
a = np.arange(1,13,1)

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
a.shape

(12,)

In [6]:
a.reshape([2,6])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
a.reshape([3,4])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### np.transpose
np.transpose는 2차원 배열의 x축과 y축을 변경해줄 때 사용합니다. np.transpose 함수에 직접 바꾸고자 하는 축을 입력해주면 해당 축을 바꿔줍니다.

In [9]:
a = np.arange(1,7,1).reshape([2,3])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a[0]

array([1, 2, 3])

In [12]:
a[0][1]

2

In [14]:
a_transpose = a.transpose()

In [18]:
a_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
a_transpose[1][0]  # 축을 뒤바꿨다

2

### ndarray 펼치기
np.flatten을 사용하면 다차원 배열을 1차원으로 펼칠 수 있다.

In [22]:

a = np.arange(1,13,1).reshape([2,3,2]) 
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [23]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 연습문제
np.reshape를 사용하여 b를 아래 형태들로 만들어 보세요

In [24]:
import numpy as np

reshape_example = np.arange(1, 13, 1)

In [25]:
reshape_example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
reshape_example.reshape([6,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [28]:
reshape_example.reshape([3,2,2])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [29]:
reshape_example.reshape([2,2,3])  # 함수에 커서 대고 shift + tab 누르면 docstring이 나옴

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])