# ch4. ndarray index & slice

### ndarray index
기본적으로 python list에서 index를 이용하여 접근하듯 다차원 배열의 각 원소들에 접근할 수 있습니다.

In [2]:
import numpy as np

In [3]:
a = np.arange(1, 13, 1).reshape([3, 2, 2])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [7]:
a[2][0][1]

10

In [8]:
a[1][0][1]

6

인덱스로 접근해서 값을 업데이트 할 수도 있습니다.

In [9]:
a[1][0][1] = 20

In [10]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5, 20],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

그리고 python과는 달리 인덱스 하나에 ,를 이어붙인 문법을 사용할 수 있습니다.

In [11]:
a[1,0,1]    
# 넘파이 문법!!!
# 파이썬 리스트에서는 이 문법 안 통함

20

### : 기호 사용해서 특정 축의 데이터 모두 선택하기
ndarray index에 : 를 사용하면 해당 축의 모든 데이터를 선택하겠다는 의미입니다.

In [56]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5, 20],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [55]:
a[1,1,:]

array([7, 8])

In [13]:
a[1]

array([[ 5, 20],
       [ 7,  8]])

In [14]:
a[1,:,1]
# 1번째 인덱스에 모든 축에서 1번째 element만 들고 오겠다

array([20,  8])

In [15]:
a[:,1]
# 모든 1번째 축에서 1번째 element만 들고 오겠다

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [16]:
a[:,:,1]
# 모든 1번째 축에서 2번째 축에서 1번째 element만 

array([[ 2,  4],
       [20,  8],
       [10, 12]])

In [17]:
a[:,:,0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

슬라이싱

In [57]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5, 20],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [19]:
a[:,1]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [59]:
a[1:3]

array([[[ 5, 20],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [21]:
a[1:3,1]

array([[ 7,  8],
       [11, 12]])

In [22]:
b = np.arange(1,13,1).reshape([6,2])

In [23]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
b[1:4]

array([[3, 4],
       [5, 6],
       [7, 8]])

In [25]:
b[1:4,0]

array([3, 5, 7])

In [26]:
b[:4,1]

array([2, 4, 6, 8])

### 연습문제

인덱스와 슬라이스를 이용해서 아래 출력을 구해보세요.

In [28]:
import numpy as np
b = np.arange(1, 28, 1).reshape([3, 3, 3])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [33]:
b[:,0,0]

array([ 1, 10, 19])

In [38]:
b[0,:,1]

array([2, 5, 8])

In [40]:
b[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
b[:,1]

array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24]])

In [43]:
b[:,:,2]

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])